### ISSUE TITLE
Contribute to translation

### ISSUE THREAD

**Issue by dorian-marchal** [concrete5/concrete5-translations#1]
Sometimes, I spot some mistakes in the french translation of Concrete5.

Can I make a pull request on this repository ? Is there an other way to fix these mistakes without beeing overriden by the next pull ?

**Comment by mlocati** [comment]
This repository is just a copy of the translations managed in transifex.
Instead of creating  pull requests here you should join the French translation group in transifex: https://www.transifex.com/projects/p/concrete5-packages/language/fr_FR/

**Comment by mlocati** [comment]
Ups, sorry. That link is for the packages  translations. For the core translations you should join https://www.transifex.com/projects/p/concrete5/language/fr_FR/

**Comment by dorian-marchal** [comment]
Nice, thank you :+1:

**Comment by mlocati** [comment]
:ok_hand:

**Comment by mlocati** [comment]
@dorian-marchal I just approved your request  to join the packages translations group.
For the core translation group you have to wait for the French  coordinator  to approve your request. If he doesn't answer  you in two weeks, I'll approve it myself.

**Comment by dorian-marchal** [comment]
My request has been approved, thank you :+1:

**Comment by mlocati** [comment]
Great! Thank you!
