### ISSUE TITLE
Files to link in Transifex issues

### ISSUE THREAD

**Issue by dorian-marchal** [concrete5/concrete5-translations#2]
If it's okay with you, I open (and close right away) this issue to upload files in order to link them in Transifex issues/comments (I will edit this post).

---

Save Layout as Preset :
![Save Layout as Preset](https://cloud.githubusercontent.com/assets/6225979/9002846/ea2c5c4c-3768-11e5-8dab-8c907a8329c1.png)

**Comment by mlocati** [comment]
Why don't you use something like http://imgur.com ?

**Comment by dorian-marchal** [comment]
Usually, I do that to keep my screenshots close to the code.
But you're right, in this case, it makes little sense and an image hosting service is probably better.
